app/__init__.py
from flask import Flask

def crear_app():
    app = Flask(__name__)

    from .routes import bp
    app.register_blueprint(bp)

    return app

app/routes.py
from flask import Blueprint, render_template, request, url_for, redirect
from app.utils.config import MONTO_MINIMO, STEP, RUTA_PAGOS, RUTA_DEUDAS
from app.utils.gestionar_json import leer, escribir

bp = Blueprint("main", __name__)

@bp.route("/")
def inicio():
    return render_template("index.html")


@bp.route("/agregar")
def agregar():
    cambio = request.args.get("cambio", default=None, type=int)
    mensaje = ""

    if cambio is not None and cambio > 0:
        mensaje = f"Debes devolver {cambio}"

    return render_template("agregar.html", cambio=mensaje, MONTO_MINIMO=MONTO_MINIMO, STEP=STEP)

@bp.route("/deudas")
def deudas():
    lista_deudas = leer(RUTA_DEUDAS)
    return render_template("deudas.html", deudas=lista_deudas)

@bp.route("/enviar", methods=["POST"])
def enviar_usuario():
    nombre = request.form["nombre"]
    dinero = request.form["dinero"]

    cambio = int(dinero) - MONTO_MINIMO

    if cambio > 0:
        archivo_deudas = leer(RUTA_DEUDAS)
        nueva = {
            "nombre": nombre,
            "cambio": cambio
        }

        archivo_deudas.append(nueva)

        escribir(archivo_deudas, RUTA_DEUDAS)

    leer_archivo = leer(RUTA_PAGOS)
    leer_archivo.append(nombre)
    escribir(leer_archivo, RUTA_PAGOS)

    return redirect(url_for("main.agregar", cambio=cambio))

@bp.route("/eliminar_deuda/<nombre>")
def eliminar_deuda(nombre):
    leer_deudas = leer(RUTA_DEUDAS)

    for d in leer_deudas:
        if d["nombre"] == nombre:
            leer_deudas.remove(d)
            break

    escribir(leer_deudas, RUTA_DEUDAS)

    return redirect(url_for("main.deudas"))

app/templates/agregar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PayLogger - Nuevo pago</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/agregar.css') }}">
    <link rel="shortcut icon" href="{{url_for('static', filename='img/logo.svg')}}" type="image/x-icon"> 
</head>
<body>
    <form action="{{ url_for('main.enviar_usuario') }}" method="post">
        <div>
            <a href="{{ url_for('main.inicio') }}"><img src="{{url_for('static', filename='img/persona.svg')}}"></a>
        </div>
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" id="nombre" required>

        <label for="dinero">Dinero dado</label>
        <input type="number" name="dinero" id="dinero" required min="{{ MONTO_MINIMO }}" step="{{ STEP }}">

        <button type="submit" class="btn-agregar">Agregar</button>

        <p>{{cambio}}</p>
    </form>
</body>
</html>

app/templates/deudas.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PayLogger - Deudas</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/deudas.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/logo.svg') }}" type="image/x-icon">
</head>
<body>
    <div class="container">
        <h1><a href="{{ url_for('main.inicio') }}">Personas a las que debes cambio</a></h1>

        {% if deudas %}
            <ul class="deudas-lista">
                {% for i in deudas %}
                    <li class="deuda-item">
                        <div class="deuda-info">
                            <span class="nombre"><a href="{{ url_for('main.eliminar_deuda', nombre=i['nombre']) }}">{{ i.nombre }}</a></span>
                            <span class="monto">Debe devolver <b>{{ i.cambio }}</b> pesos</span>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="sin-deudas">No tienes deudas registradas</p>
        {% endif %}
    </div>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PayLogger</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <link rel="shortcut icon" href="{{url_for('static', filename='img/logo.svg')}}" type="image/x-icon">
</head>
<body>
  <div class="cards" id="c1">
    <img src="{{url_for('static', filename='img/lista.svg')}}" alt="imagen de lista">
    
    <div>
      <h1>Nuevo Pago</h1>
      <p>Agregar estudiante a la lista de pagos realizados</p>
      <button><a href="{{ url_for('main.agregar') }}">Agregar</a></button>
    </div>
  </div>

  <div class="cards" id="c2">
    <img src="{{url_for('static', filename='img/deuda.svg')}}" alt="imagen de lista">
    
    <div>
      <h1>Deudas</h1>
      <p>Mostrar a los estudiantes que hay que devolverles dinero</p>
      <button><a href="{{ url_for('main.deudas') }}">Mostras</a></button>
    </div>
  </div>
</body>
</html>